# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: Parareal in Python

plugins:
  - search
  - bibtex:
      bib_file: "docs/paper.bib"

markdown_extensions:
   - pymdownx.superfences
   - admonition
   - def_list
   - footnotes
   - pymdownx.arithmatex:
      generic: true
   - toc:
        permalink: true

theme:
  name: material
  features:
    - content.code.annotate
  palette:
      # Palette toggle for light mode
      - scheme: default
        primary: pink 
        toggle:
          icon: material/brightness-7 
          name: Switch to dark mode
  
      # Palette toggle for dark mode
      - scheme: slate
        primary: pink  
        toggle:
          icon: material/brightness-4
          name: Switch to light mode

extra_javascript:
    - javascripts/mathjax.js
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
