on: [push]

jobs:
  install:
    runs-on: ubuntu-latest
    name: Test package installation
    steps:
    - name: Checkout this
      id: checkout-this
      uses: actions/checkout@v2

    - name: Install packages
      id: install-packages
      run: |
        sudo apt-get install -y python3.9 python3-pip python3-testresources

    - name: Install poetry
      id: install-poetry
      run: |
        pip install --user poetry

    - name: Create env
      id: create-env
      run: |
        poetry install -v

    - name: Run tests
      id: run-tests
      run: |
        poetry run pytest
      shell: bash

  openfoam_job:
    runs-on: ubuntu-latest
    name: A job to test OpenFOAM
    steps:
    - name: Checkout this
      id: checkout-this
      uses: actions/checkout@v2

    - name: Install packages
      id: install-packages
      run: |
        sudo add-apt-repository ppa:deadsnakes/ppa
        sudo curl -s https://dl.openfoam.com/add-debian-repo.sh | sudo bash
        sudo apt-get install -y python3.9 python3-pip openfoam2106-default python3-testresources

    - name: Install poetry
      id: install-poetry
      run: |
        pip install --user poetry

    - name: Create env
      id: create-env
      run: |
        poetry install -v

    - name: Run tests
      id: run-tests
      run: |
        set +o pipefail
        source /usr/lib/openfoam/openfoam2106/etc/bashrc || true
        poetry run pytest
      shell: bash
